env:
  browser: true
  node: true
plugins:
  - prettier
extends:
  - eslint:recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 2015
  sourceType: module
rules:
  prettier/prettier: error
